disabled_rules:
- todo
- force_cast
- trailing_whitespace
- trailing_comma
- opening_brace
- class_delegate_protocol
- redundant_optional_initialization
- function_body_length
- line_length

indentation_width: 4

force_unwrapping:
  severity: error

function_body_length:
- 10 # warning
- 25 # error

type_body_length:
- 200 # warning
- 400 # error

line_length:
- 150 # warning
- 200 # error

opt_in_rules:
- force_unwrapping
- indentation_width
- sorted_imports
- multiline_arguments
- multiline_parameters_brackets
