spring:
  profiles:
    active: local
    group:
      local: [ db-local, local ]
      prod: [ prod ]
      dev: [ dev ]
    include: [ aws, jwt, oauth ]
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
