spring:
  profiles:
    active: dev
    group:
      local: [ db-local, local ]
      prod: [ prod ]
      dev: [ dev ]
    include: [ aws, jwt, oauth ]
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
