spring:
  profiles:
    active:
      - dev
    group:
      local:
        - db-local
      prod:
        - prod
      dev:
        - dev
    include:
      - aws
      - jwt
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
logging:
  level:
    com.team5.secondhand: debug
